// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VccMgntSys;

#nullable disable

namespace VccMgntSys.Migrations
{
    [DbContext(typeof(MainDatabase))]
    [Migration("20240928081129_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CitizenVaccineProgram", b =>
                {
                    b.Property<Guid>("CitizensId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaccineProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("CitizensId", "VaccineProgramId");

                    b.HasIndex("VaccineProgramId");

                    b.ToTable("CitizenVaccineProgram");
                });

            modelBuilder.Entity("StaffVaccineProgram", b =>
                {
                    b.Property<Guid>("StaffsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaccineProgramsId")
                        .HasColumnType("uuid");

                    b.HasKey("StaffsId", "VaccineProgramsId");

                    b.HasIndex("VaccineProgramsId");

                    b.ToTable("StaffVaccineProgram");
                });

            modelBuilder.Entity("VaccineBatchVaccineProgram", b =>
                {
                    b.Property<Guid>("VaccineBatchesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaccineProgramsId")
                        .HasColumnType("uuid");

                    b.HasKey("VaccineBatchesId", "VaccineProgramsId");

                    b.HasIndex("VaccineProgramsId");

                    b.ToTable("VaccineBatchVaccineProgram");
                });

            modelBuilder.Entity("VccMgntSys.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateofBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsSuperAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("StringCitizenID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("VccMgntSys.Models.Citizen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CitizenID")
                        .HasColumnType("bigint");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherDiseases")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Pending")
                        .HasColumnType("boolean");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("ReportData")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("VaccinationCount")
                        .HasColumnType("integer");

                    b.Property<string>("VaccinationDate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("citizens");
                });

            modelBuilder.Entity("VccMgntSys.Models.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateofBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HospitalID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("VccMgntSys.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Confirm")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VaccineProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("VaccineProgramId");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("VccMgntSys.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateofBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HospitalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("VccMgntSys.Models.Statistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Datadate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalPrograms")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalVaccinations")
                        .HasColumnType("bigint");

                    b.Property<long>("VaccinatedCitizens")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("statistics");
                });

            modelBuilder.Entity("VccMgntSys.Models.VaccineBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProducedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("vaccineBatches");
                });

            modelBuilder.Entity("VccMgntSys.Models.VaccineProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("vaccinePrograms");
                });

            modelBuilder.Entity("CitizenVaccineProgram", b =>
                {
                    b.HasOne("VccMgntSys.Models.Citizen", null)
                        .WithMany()
                        .HasForeignKey("CitizensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VccMgntSys.Models.VaccineProgram", null)
                        .WithMany()
                        .HasForeignKey("VaccineProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StaffVaccineProgram", b =>
                {
                    b.HasOne("VccMgntSys.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VccMgntSys.Models.VaccineProgram", null)
                        .WithMany()
                        .HasForeignKey("VaccineProgramsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VaccineBatchVaccineProgram", b =>
                {
                    b.HasOne("VccMgntSys.Models.VaccineBatch", null)
                        .WithMany()
                        .HasForeignKey("VaccineBatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VccMgntSys.Models.VaccineProgram", null)
                        .WithMany()
                        .HasForeignKey("VaccineProgramsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VccMgntSys.Models.Message", b =>
                {
                    b.HasOne("VccMgntSys.Models.Citizen", "Citizen")
                        .WithMany()
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VccMgntSys.Models.VaccineProgram", "VaccineProgram")
                        .WithMany()
                        .HasForeignKey("VaccineProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("VaccineProgram");
                });

            modelBuilder.Entity("VccMgntSys.Models.VaccineProgram", b =>
                {
                    b.HasOne("VccMgntSys.Models.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });
#pragma warning restore 612, 618
        }
    }
}
